# Generated by Django 6.0 on 2026-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('product_display_name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Boys', 'Boys'), ('Girls', 'Girls'), ('Unisex', 'Unisex')], max_length=50)),
                ('master_category', models.CharField(db_index=True, max_length=100)),
                ('sub_category', models.CharField(db_index=True, max_length=100)),
                ('article_type', models.CharField(db_index=True, max_length=100)),
                ('base_colour', models.CharField(max_length=50)),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('usage', models.CharField(choices=[('Casual', 'Casual'), ('Smart Casual', 'Smart Casual'), ('Formal', 'Formal'), ('Party', 'Party'), ('Sports', 'Sports'), ('Travel', 'Travel')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
