# Generated by Django 6.0 on 2026-01-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('product_id', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('master_category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('article_type', models.CharField(max_length=50)),
                ('base_colour', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('usage', models.CharField(max_length=50)),
                ('product_display_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/images/')),
            ],
            bases=('core.timestampedmodel',),
        ),
    ]
